// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGhFGT6fh3EjxhuAb4sUxWAMS4xQdiUTE',
    appId: '1:225193671045:web:25577cea4d4c7a46daacec',
    messagingSenderId: '225193671045',
    projectId: 'fir-push-notification-a9e08',
    authDomain: 'fir-push-notification-a9e08.firebaseapp.com',
    storageBucket: 'fir-push-notification-a9e08.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGdvgbFNSdZF7xAM1HHGVSmnxDhk9EuN4',
    appId: '1:225193671045:android:a2d12c3b73358554daacec',
    messagingSenderId: '225193671045',
    projectId: 'fir-push-notification-a9e08',
    storageBucket: 'fir-push-notification-a9e08.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFSusvabjCXhjAuZU-fVeJxcVW1LzqLA4',
    appId: '1:225193671045:ios:b9e931d324f1b457daacec',
    messagingSenderId: '225193671045',
    projectId: 'fir-push-notification-a9e08',
    storageBucket: 'fir-push-notification-a9e08.appspot.com',
    iosBundleId: 'com.futuresoftindia.pushnotificationApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFSusvabjCXhjAuZU-fVeJxcVW1LzqLA4',
    appId: '1:225193671045:ios:97c85a3215ea8d5adaacec',
    messagingSenderId: '225193671045',
    projectId: 'fir-push-notification-a9e08',
    storageBucket: 'fir-push-notification-a9e08.appspot.com',
    iosBundleId: 'com.futuresoftindia.pushnotificationApp.RunnerTests',
  );
}
